# Generated by Django 4.1.4 on 2023-02-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desciption',
            new_name='description',
        ),
    ]
